# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kretsula
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: spacebring
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shop

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  hello_world:
    handler: handler.hello_world
    events:
      - httpApi:
          path: /hello_world
          method: get
