# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kretsula
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: spacebring
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shop

plugins:
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    PRODUCTS_TABLE: ProductsTableV2
    JWT_SECRET: ${env:JWT_SECRET, 'super-secret-jwt-key-change-in-production'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:us-east-1:*:table/${self:provider.environment.PRODUCTS_TABLE}

functions:
  jwtAuthorizer:
    handler: authorizers/jwtAuthorizer.handler
  generateToken:
    handler: authorizers/generateToken.handler
    events:
      - http:
          path: /auth/token
          method: get
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  hello_world:
    handler: handlers/hello_world.hello_world
    events:
      - http:
          path: hello_world
          method: get
  createProduct:
    handler: handlers/products/create.createProduct
    events:
      - http:
          path: products
          method: post
          authorizer: jwtAuthorizer
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getProduct:
    handler: handlers/products/get.getProduct
    events:
      - http:
          path: products/{id}
          method: get
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  updateProduct:
    handler: handlers/products/update.updateProduct
    events:
      - http:
          path: products/{id}
          method: put
          authorizer: jwtAuthorizer
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  deleteProduct:
    handler: handlers/products/delete.deleteProduct
    events:
      - http:
          path: products/{id}
          method: delete
          authorizer: jwtAuthorizer
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  listProducts:
    handler: handlers/products/list.listProducts
    events:
      - http:
          path: products
          method: get
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  Resources:
    ProductsTableV2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTableV2
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: category # Partition key
            KeyType: HASH
          - AttributeName: id       # Sort key
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
